### PR TITLE
code cleanup, fix mobile margin, and multiselect placeholder opacity

### LINKED ISSUE #243: [Mobile] Application page header overlaps with title
### Description

Application page header overlaps with title on small screens.

### Context

- **Browser**:  Chrome
- **OS**: iOS on iPhone X

### Steps to Reproduce

1. Visit https://commit-staging.dev/apply

IMG_5460
IMG_5461

### PR DESCRIPTION
**Pull request by ALukonin**
## Reminder

> Please ensure the following criteria is met for this PR. It will help others review your PR and provide confidence things work as expected.

- [x] CI is green
- [x] Link to any related issues
- [x] Received at least 1 approval from core members
- [x] Made sure that changes are obvious for the reviewer (ex meaningful title and commit messages, comments in code or PR where appropriate, screenshots, etc.)

# What Changed?

Added the required margin for mobile screen dimensions, matched opacity and font color for the multiselect
> Related Issue: None / [https://github.com/commitdev/commit.dev/issues/243](243)

- TODO

## Screenshots
Before:
image
After:
image

### CODE REVIEW

**Comment by alebiavati** [comment]
@anikey Could you please review this design?

File: pages/apply.js [hunk 1]
```diff
@@ -1,81 +1,18 @@
-import styled from 'styled-components'
-
-import { Heading, Form, Page } from 'components'
-import { MOBILE_SIZE, TABLET_LARGE_SIZE } from 'styles/constants'
-
-const HeroSection = styled.section`
```
Comment (alebiavati) [inline pages/apply.js:6]: I thought we were using styled components for consistency

Comment (ALukonin) [reply pages/apply.js:6]: I followed the structure of the home and about pages. We should make a standard, and I can make the changes. This can be a fix before launch, however?

**Comment by anikey** [comment]
> @anikey Could you please review this design?

Looks good, can we increase the line height for the third field?

**Comment by ALukonin** [comment]
@anikey made the change, thoughts?
image
To:
image
image

**Comment by anikey** [comment]
looks good! @ALukonin

**Review by alebiavati — APPROVED** [review]
